### ISSUE TITLE
error in utils.py

### ISSUE THREAD

**Issue by crrobles2** [pinax/pinax-wiki#10]
`  File "/home/XXX/lib/python2.6/site-packages/wiki/utils.py", line 7`
 `   for x in settings.WIKI_BINDERS`
`      ^`
`SyntaxError: invalid syntax`

Full code from utils.py:

`from .conf import settings`

`def binders_map():`
`    return {`
`        x.bind_to_model_name: x`
`        for x in settings.WIKI_BINDERS`
`    }`

`def object_slug(wiki):`
`    if wiki:`
`        slug = wiki.content_type.model`
`    else:`
`        slug = "default"`
`    return slug`

**Comment by paltman** [comment]
@crrobles2 what version of Python are you running?

**Comment by paltman** [comment]
Oh, I see, `python2.6`. This version is not supported.
