### ISSUE TITLE
Creole requirement fails when using Python 3

### ISSUE THREAD

**Issue by sargentstudley** [pinax/pinax-wiki#11]
Creole creates an error when running step: 
```bash
pip install -r requirements.txt
```
Error in terminal when using python 3.4.3 in virtualenv: 

```bash
Collecting creole
  Using cached creole-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/77/9fknv29s0gl41xyznf7mrs3m0000gp/T/pip-build-e8cn8h21/creole/setup.py", line 4, in <module>
        import creole
      File "/private/var/folders/77/9fknv29s0gl41xyznf7mrs3m0000gp/T/pip-build-e8cn8h21/creole/creole/__init__.py", line 28, in <module>
        from creole.rules import Rules
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/77/9fknv29s0gl41xyznf7mrs3m0000gp/T/pip-build-e8cn8h21/creole
```

Attempting `pip install creole` fails as well leading me to believe this is an error with the creole library's pypy listing - but this is conjecture at this time. 

Telling virtualenv to use python 2 explicitly using `virtualenv -p /usr/bin/python pinaxwikienv` (on mac os x) resolves the issue and the project works as expected.

**Comment by paltman** [comment]
Fixed in 4b4930d85fc029a4ea5300c3aa37ef13a40bc682 by using a different creole package
