### ISSUE TITLE
Setup instructions spotty

### ISSUE THREAD

**Issue by dottenbr** [pinax/pinax-wiki#16]
I was trying to find out how to set up the wiki correctly but the instructions are not complete.

I saw that I need to add "wiki" to `INSTALLED_APPS` (shouldn't it be "pinax.wiki" for consistency?) and then I was trying to figure what I have to add to urls.py. From `url(r"^blog/", include("pinax.blog.urls"))` I abstracted that it must be `url(r"^blog/", include("pinax.wiki.urls"))` which is what I added.

Then I ran `python manage.py migrate`,  `python manage.py loaddata sites` and `python manage.py runserver`.

Unfortunately it breaks with `ImportError at /admin/ No module named wiki.urls" so I just stopped there. Also running the server throws "WARNINGS: wiki.Revision.created_ip: (fields.W900) IPAddressField has been deprecated. Support for it (except in historical migrations) will be removed in Django 1.9. HINT: Use GenericIPAddressField instead.`

**Comment by paltman** [comment]
@dottenbr you are so right. we need to fix this. let me see how much I can get done before dinner.

**Comment by paltman** [comment]
@dottenbr while instructions were not addressed in 4b4930d85fc029a4ea5300c3aa37ef13a40bc682, I did address other things you referenced, naming the `pinax.wiki` namespace and ip address field issues.

**Comment by paltman** [comment]
@dottenbr until I get to documenting this project properly, you can take a look at (or just use) the wiki starter project - https://github.com/pinax/pinax-starter-projects/tree/wiki

**Comment by KatherineMichel** [comment]
Closing because issues were dealt with. We still need to add complete docs, but there is already an open issue for that.
