### ISSUE TITLE
ImproperlyConfigured bug

### ISSUE THREAD

**Issue by yn-coder** [pinax/pinax-wiki#9]
I've install the project-wiki, and got the ImproperlyConfigured bug

![improperlyconfigured at - google chrome_2014-08-22_01-18-22](https://cloud.githubusercontent.com/assets/8451944/4003656/c62b6314-2978-11e4-8d8a-f412a12c2ae0.png)

This error is from

```
url(os.path.join(binder.root, r"(?P<slug>[^/]+)/edit/$"), "edit", {"binder": binder}, name=binder.edit_url_name),
```

line from c:\Python27\Lib\site-packages\wiki\urls.py file

Python 2.7.8, django 1.6.5

**Comment by ossanna16** [comment]
@yn-coder Has this issue been solved?

**Comment by grahamu** [comment]
This is now covered by conf.py and default binders.
